name: CI Project

on:
  push:
    branches:
      - main
    paths:
      - project/**
      - tests/**
  workflow_dispatch:

jobs:
  building:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Handling Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make pipeline.sh executable
        run: |
          chmod +x project/pipeline.sh

      - name: Run Shell pipeline script
        working-directory: project
        run: |
          ./pipeline.sh

      - name: Verification of Downloaded Files
        run: |
          echo "Files in data directory:"
          ls -1 data

      - name: Run tests
        run: |
          pytest -s